
WARNING: version mismatch between CFITSIO header (v3.37) and linked library (v3.36).


WARNING: version mismatch between CFITSIO header (v3.37) and linked library (v3.36).

/home/zonca/p/software/so_pysm_models/so_pysm_models/utils/__init__.py:24: UserWarning: Access data from /simons/scratch/zonca/simonsobs/so_pysm_models_data/ame1_T_ns4096.fits
  warnings.warn(f"Access data from {full_path}")
/home/zonca/p/software/so_pysm_models/so_pysm_models/utils/__init__.py:24: UserWarning: Access data from /simons/scratch/zonca/simonsobs/so_pysm_models_data/ame_emissivity.txt
  warnings.warn(f"Access data from {full_path}")
/home/zonca/p/software/so_pysm_models/so_pysm_models/utils/__init__.py:24: UserWarning: Access data from /simons/scratch/zonca/simonsobs/so_pysm_models_data/variable_spectral_index/ame_nu0_peak_ns4096_1deg.fits
  warnings.warn(f"Access data from {full_path}")
/home/zonca/p/software/so_pysm_models/so_pysm_models/utils/__init__.py:24: UserWarning: Access data from /simons/scratch/zonca/simonsobs/so_pysm_models_data/dust_Q_ns4096.fits
  warnings.warn(f"Access data from {full_path}")
/home/zonca/p/software/so_pysm_models/so_pysm_models/utils/__init__.py:24: UserWarning: Access data from /simons/scratch/zonca/simonsobs/so_pysm_models_data/dust_U_ns4096.fits
  warnings.warn(f"Access data from {full_path}")
/home/zonca/p/software/pysm/pysm/models/template.py:308: UserWarning: No physical unit associated with file /simons/scratch/zonca/simonsobs/so_pysm_models_data/dust_U_ns4096.fits
  warnings.warn("No physical unit associated with file " + str(path))
/home/zonca/p/software/pysm/pysm/models/template.py:308: UserWarning: No physical unit associated with file /simons/scratch/zonca/simonsobs/so_pysm_models_data/dust_Q_ns4096.fits
  warnings.warn("No physical unit associated with file " + str(path))
/home/zonca/p/software/so_pysm_models/so_pysm_models/utils/__init__.py:24: UserWarning: Access data from /simons/scratch/zonca/simonsobs/so_pysm_models_data/ame2_T_ns4096.fits
  warnings.warn(f"Access data from {full_path}")
/home/zonca/p/software/so_pysm_models/so_pysm_models/utils/__init__.py:24: UserWarning: Access data from /simons/scratch/zonca/simonsobs/so_pysm_models_data/ame_emissivity.txt
  warnings.warn(f"Access data from {full_path}")
/home/zonca/p/software/so_pysm_models/so_pysm_models/utils/__init__.py:24: UserWarning: Access data from /simons/scratch/zonca/simonsobs/so_pysm_models_data/dust_Q_ns4096.fits
  warnings.warn(f"Access data from {full_path}")
/home/zonca/p/software/so_pysm_models/so_pysm_models/utils/__init__.py:24: UserWarning: Access data from /simons/scratch/zonca/simonsobs/so_pysm_models_data/dust_U_ns4096.fits
  warnings.warn(f"Access data from {full_path}")

real	75m55.702s
user	3456m10.850s
sys	61m44.869s
